config/routes.rb
Mercurio::Application.routes.draw do

  resources :museum_items

  resources :genres
  resources :media_types
  
  resources :medias do
    member do
      get 'lend' => 'loans#new'
      get 'return' => 'loans#return'
      get 'cofirm_return' => 'loans#confirm_return'
    end
  end
  
  get 'loans' => "loans#index", :as => :loans
  post 'loans' => "loans#create", :as => :loans
  
  get 'people/emails' => "people#emails", :as => :emails
  
  resources :people 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  root :to => "home#index"
  match 'construcao' => "home#construcao"

end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :media_type, :foreign_key => 'media_type_id'
  belongs_to :genre
  belongs_to :media_status
  has_many :loans, :order => 'id ASC'

  default_scope order('title')
  scope :list, joins(:genre)

  validates_length_of :title, :minimum => 3
  validates_presence_of :title
  validates_presence_of :author  
  validates_presence_of :genre
  validates_presence_of :media_type
  validates_numericality_of :price, :allow_nil => true
  validates_numericality_of :code
  validates_uniqueness_of :code, :scope => [:genre_id]  

  before_validation :upcase_title_and_author
  
  def abbreviated_title
    return excerpt(self.title,:radius => 5)
  end
  
  def upcase_title_and_author     
     self.title.upcase! unless self.title.nil?
     self.author.upcase! unless self.author.nil?
  end
  
  def formatted_code
    "%04d" % self.code
  end
  
  def full_code
    self.genre.acronym + '-' + self.formatted_code
  end
  
  def self.by_code(query, page = 1)
    acronym = query[0..2]
    code = self.get_numbers query
    
  end
  
  def self.search(query, page = 1)    
    if query      
      acronym = query[0..2]
      code = self.get_numbers query
      
      medias = Media.list.includes(:media_type).includes(:genre)
        .where('genres.acronym = upper(:acronym) and code = :code', :code => code ,:acronym => acronym)
        .paginate :page => page, :per_page => 50
      
      if medias.empty? then
        medias = Media.list.includes(:media_type).includes(:genre)
        .where('''title LIKE upper(:query) 
                  or author LIKE upper(:query) 
                  or genres.acronym = upper(:acronym) 
                  or code = :code
                  or media_types.name LIKE upper(:query)''', 
                  :query => "%#{query}%",
                  :code => code,
                  :acronym => acronym)
        .paginate :page => page, :per_page => 50
      end
    else
      medias = Media.list.includes(:media_type).includes(:genre).paginate :page => page, :per_page => 50
    end
    return medias
  end
  
  def last_loan
    self.loans.first
  end
  
  def available?
    self.media_status.nil? or self.media_status.try(:available?)
  end
  
  def lent?
    self.media_status.try(:lent?)
  end
  
  def lend
    update_status(2)
  end
  
  def return
    update_status(1)
  end
  
  private
  
  def update_status(media_status_id)
    self.media_status = MediaStatus.find(media_status_id)
    self.save
  end
  
  def self.get_numbers(query)
    query.scan(/\d/).join.to_i unless query.nil?
  end
      
end

app/models/media_type.rb
class MediaType < ActiveRecord::Base

  default_scope order('name')  
  attr_protected :name
  validates_numericality_of :loan_days
  validates_presence_of :loan_days
  
  def to_s
    "#{name}"
  end
  
end

app/controllers/medias_controller.rb
class MediasController < InheritedResources::Base
    
  def index
    @medias = Media.search(params[:query], params[:page])
  end
  
  def new
    @media_types = MediaType.all
    @genres = Genre.all
    super
  end 
  
  def create
    @media_types = MediaType.all
    @genres = Genre.all
    super
  end
  
  def edit
    @media_types = MediaType.all
    @genres = Genre.all
    super
  end
  
  def update
    @media_types = MediaType.all
    @genres = Genre.all
    super
  end
  
end

app/helpers/medias_helper.rb
module MediasHelper
end

app/views/medias/_form.html.haml
%div.form.span-24
	= form_for @media do |f|  
		- if @media.errors.any?
			%div#error_explanation.error
				%h2= t(:pending, :count => @media.errors.count)
				%ul
					- @media.errors.full_messages.each do |msg|
						%li= msg
		%div.span-12
			= f.label t(:title)
			= f.text_field :title, :size => 80
		%div.span-10.last
			= f.label t(:author)	
			= f.text_field :author, :size => 45
		%div.span-4
			= f.label t(:media_type) 
			= f.select(:media_type_id,  options_from_collection_for_select(@media_types, :id, :name, (unless @media.media_type.nil? then @media.media_type.id end ))) 
		%div.span-2
			= f.label t(:genre) 
			= f.select(:genre_id,  options_from_collection_for_select(@genres, :id, :acronym, (unless @media.genre.nil? then @media.genre.id end ))) 
		%div.span-6
			= f.label t(:code)
			= f.text_field(:code, :size => "15", :class => "span-7") 	
		%div.span-3
			= f.label t(:price) 
			= f	.text_field(:price, :size => "7", :class => "span-7") 
		%div.span-8
			= f.label t(:duration) 
			= f.text_field(:time, :size => "3", :class => "span-5") 			
		%div.span-18.clear
			= f.label t(:description) 
			= f.text_area :description, :class => 'description' 
		%div.clear.actions
			= f.hidden_field(:media_status_id, :value => 1) 
			= f.submit 

app/views/medias/edit.html.erb
<h1><%=t :editing %> <%=t :media%></h1>

<%= render 'form' %>


<%= link_to t(:show), @media, :class => 'button' %>
<%= link_to t(:back), medias_path, :class => 'button' %>

app/views/medias/index.html.erb
<h1><%=t :listing%> <%=t(:medias)%></h1>

<div class="span-20">
<%= form_tag medias_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :query, params[:query], :size => 80 %>
    <%= positive_button_submit_tag "Buscar" %>
	<br>
	<%= @medias.total_entries %> mídia(s) encontrada(s).
  </p>
<% end %>
</div>
<div class="span-3">
	<%= add_button_link_to "#{t(:new)} #{t(:media)}", new_media_path %>
</div>

<table class="grade clear">
  <tr>
	<th><%= t(:code) %></th>
    <th><%= t(:title) %></th>
    <th><%= t(:media_type) %></th>
	<th><%= t(:media_status) %></th>
    <th></th>
  </tr>

<% @medias.each do |media| %>
  <tr class="<%= cycle('odd', 'even') %>">
	<td><%= media.full_code %></td>
    <td title="<%= media.title %>"><%= truncate(media.title, :length => 50) %></td>
    <td><%= media.media_type.name unless media.media_type.nil? %></td>
	<td><%= media.media_status.description unless media.media_status.nil? %></td>
	<td>
		<%= button_group do %>		
			<%= pill_positive_button_link_to t(:lend), lend_media_path(media) if media.available?%>
			<%= pill_positive_button_link_to t(:return), return_media_path(media) if media.lent?%>
			<%= pill_button_link_to t(:show), media %>
			<%= pill_button_link_to t(:edit), edit_media_path(media) %>
			<%= pill_negative_button_link_to t(:destroy), media, :confirm => 'Tem certeza?', :method => :delete %>
		<% end %>
	</td>
  </tr>
<% end %>
</table>

<%= will_paginate @medias %>

app/views/medias/new.html.erb
<h1><%= t(:new) %> <%= t(:media) %></h1>

<%= render 'form' %>

<%= link_to t(:back), medias_path, :class => 'button' %>

app/views/medias/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @media.title %></h2>

<p class='info'>
  <b><%=t :status %>:</b>
  <%= @media.media_status.try(:description) %>
  <% if @media.lent? %>
	para <%= @media.last_loan.person.name %>
  <% end %>
</p>


<p>
  <b><%=t :author %>:</b>
  <%= @media.author %>
</p>

<p>
  <b><%=t :code %>:</b>
  <%= @media.full_code %>
</p>

<p>
  <b><%=t :media_type %>:</b>
  <%= @media.media_type %>
</p>

<p>
  <b><%=t :status %>:</b>
  <%= @media.media_status.try(:description) %>
</p>

<p>
  <b><%=t :genre %>:</b>
  <%= @media.genre.name %>
</p>

<p>
  <b><%=t :description %>:</b>
  <%= @media.description %>
</p>

<p>
  <b><%=t :duration %>:</b>
  <%= @media.time %>
</p>

<%= link_to t(:edit) , edit_media_path(@media), :class => 'button' %> 
<%= link_to t(:back) , medias_path, :class => 'button' %>

<br/><br/><br/><br/>
<p>
	<%= link_to "#{t(:new)} #{t(:media)}", new_media_path, :class => 'button' %>
</p>