config/routes.rb
Mercurio::Application.routes.draw do

  resources :museum_items

  resources :genres
  resources :media_types
  
  resources :medias do
    member do
      get 'lend' => 'loans#new'
      get 'return' => 'loans#return'
      get 'cofirm_return' => 'loans#confirm_return'
    end
  end
  
  get 'loans' => "loans#index", :as => :loans
  post 'loans' => "loans#create", :as => :loans
  
  get 'people/emails' => "people#emails", :as => :emails
  
  resources :people 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  root :to => "home#index"
  match 'construcao' => "home#construcao"

end

app/controllers/media_types_controller.rb
class MediaTypesController < InheritedResources::Base
  
  actions :index, :show, :edit, :update
  
end

app/views/media_types/_form.html.erb
<%= form_for(@media_type) do |f| %>
  <% if @media_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media_type.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @media_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= @media_type.name %></h3>

  <div class="field">
    <%= f.label t(:loan_days) %><br />
    <%= f.text_field :loan_days %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media_types/edit.html.erb
<h1><%= "#{t(:editing)} #{t(:media_type)}"%></h1>

<%= render 'form' %>

<%= link_to t(:show), @media_type, :class => 'button' %> 
<%= link_to t(:back), media_types_path, :class => 'button' %>

app/views/media_types/index.html.erb
<h1><%= "#{t(:listing)} #{t(:media_types)}" %></h1>

<table>
  <tr>
    <th><%= t(:name)%></th>
	<th><%= t(:loan_days)%></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @media_types.each do |media_type| %>
  <tr class="<%= cycle('odd', 'even') %>">
	<td><%= media_type.name %></td>
	<td><%= media_type.loan_days %></td>
    <td><%= link_to t(:show), media_type, :class => 'button' %></td>
    <td><%= link_to t(:edit), edit_media_type_path(media_type), :class => 'button' %></td>
  </tr>
<% end %>
</table>

app/views/media_types/new.html.erb
<h1><%= t(:new) %> <%= t(:media_type) %></h1>

<%= render 'form' %>

<%= link_to t(:back), genres_path, :class => 'button' %>

app/views/media_types/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @media_type.name %></h1>

<p>
  <b><%= t(:loan_days)%>:</b>
  <%= @media_type.loan_days %>
</p>



<%= link_to t(:edit), edit_media_type_path(@media_type), :class => 'button' %> 
<%= link_to t(:back), media_types_path, :class => 'button' %>