config/routes.rb
Mercurio::Application.routes.draw do

  resources :museum_items

  resources :genres
  resources :media_types
  
  resources :medias do
    member do
      get 'lend' => 'loans#new'
      get 'return' => 'loans#return'
      get 'cofirm_return' => 'loans#confirm_return'
    end
  end
  
  get 'loans' => "loans#index", :as => :loans
  post 'loans' => "loans#create", :as => :loans
  
  get 'people/emails' => "people#emails", :as => :emails
  
  resources :people 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  root :to => "home#index"
  match 'construcao' => "home#construcao"

end

app/models/museum_item.rb
class MuseumItem < ActiveRecord::Base

  validates_presence_of :name, :inventory_number

  attr_accessible :acquisition_date, :depth, :description, :height, :material, :name, :origin, :width, :picture, :inventory_number, :status, :notes
  has_attached_file :picture, :styles => { :medium => "360x270>", :thumb => "64x48>" }, :default_url => "/images/missing.png"
  
  def self.search(query, page = 1)    
    if query
      MuseumItem.where('upper(name) LIKE upper(:query) or inventory_number LIKE upper(:query)', :query => "%#{query}%").paginate :page => page, :per_page => 50
    else
      MuseumItem.paginate :page => page, :per_page => 20
    end
  end
end

app/controllers/museum_items_controller.rb
class MuseumItemsController < InheritedResources::Base

  def index
    @museum_items = MuseumItem.search(params[:query], params[:page])
  end
end

app/helpers/museum_items_helper.rb
module MuseumItemsHelper
end

app/views/museum_items/_form.html.erb
<%= form_for @museum_item, :html => { :multipart => true } do |f| %>
  <% if @museum_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @museum_item.errors.count %> erro(s) ao salvar:</h2>

      <ul>
      <% @museum_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="float:right">
	<%= image_tag @museum_item.picture.url(:medium) %>
  </div>

  <div class="field">
    <%= f.label :inventory_number %><br />
    <%= f.text_field :inventory_number, :size => 15 %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 100 %>
  </div>
  <div class="field">
    <%= f.label :acquisition_date %><br />
    <%= f.text_field :acquisition_date, :size => 15 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :origin %><br />
    <%= f.text_field :origin %>
  </div>  
  <div class="field">
    <%= f.label :material %><br />
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height, :size => 10 %> cm
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.text_field :width, :size => 10 %> cm
  </div>
  <div class="field">
    <%= f.label :depth %><br />
    <%= f.text_field :depth, :size => 10 %> cm
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<br/>
<br/>

app/views/museum_items/edit.html.erb
<h1><%= t(:editing) %> <%= t(:museum_item) %></h1>

<%= render 'form' %>

<%= link_to t(:back), museum_items_path, :class => :button %>
<%= link_to t(:show), @museum_item, :class => :button %>

app/views/museum_items/index.html.erb
<h1><%=t :listing%> <%=t(:museum_items)%></h1>

<div class="span-19">
<%= form_tag museum_items_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :query, params[:query], :size => 80 %>
    <%= positive_button_submit_tag "Buscar" %>
	<br>
	<%= @museum_items.total_entries %> item(ns) encontrado(s).
  </p>
<% end %>
</div>
<div class="span-4">
	<%= add_button_link_to "#{t(:new)} #{t(:museum_item)}", new_museum_item_path %>
</div>

<table class="grade clear">
  <tr>
	<th><%= t('activerecord.attributes.museum_item.picture') %></th>
	<th><%= t('activerecord.attributes.museum_item.inventory_number') %></th>
	<th><%= t('activerecord.attributes.museum_item.name') %></th>
	<th><%= t('activerecord.attributes.museum_item.acquisition_date') %></th>
    <th></th>
  </tr>

<% @museum_items.each do |museum_item| %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= image_tag museum_item.picture.url(:thumb) %></td>
    <td><%= museum_item.inventory_number %></td>
    <td title='<%= museum_item.name %>'><%= museum_item.name.truncate(40) %></td>
    <td><%= museum_item.acquisition_date %></td>
	<td>
		<%= button_group do %>
			<%= pill_button_link_to t(:show), museum_item %>
			<%= pill_button_link_to t(:edit), edit_museum_item_path(museum_item) %>
			<%= pill_negative_button_link_to t(:destroy), museum_item, :confirm => 'Tem certeza?', :method => :delete %>
		<% end %>
	</td>
  </tr>
<% end %>
</table>

<%= will_paginate @museum_items %>

app/views/museum_items/new.html.erb
<h1><%= t(:new) %> <%= t(:museum_item) %></h1>

<%= render 'form' %>

<%= link_to t(:back), museum_items_path, :class => :button %>

app/views/museum_items/show.html.erb
<p id="notice"><%= notice %></p>

<div style="float:right">
  <%=link_to image_tag(@museum_item.picture.url(:medium)), @museum_item.picture.url(:original) %>
</div>

<p>
  <b><%= t('activerecord.attributes.museum_item.inventory_number') %></b>
  <%= @museum_item.inventory_number %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.name') %></b>
  <%= @museum_item.name %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.acquisition_date') %></b>
  <%= @museum_item.acquisition_date %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.description') %></b>
  <%= @museum_item.description %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.origin') %></b>
  <%= @museum_item.origin %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.material') %></b>
  <%= @museum_item.material %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.status') %></b>
  <%= @museum_item.status %>
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.height') %></b>
  <%= @museum_item.height %> cm
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.width') %></b>
  <%= @museum_item.width %> cm
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.depth') %></b>
  <%= @museum_item.depth %> cm
</p>

<p>
  <b><%= t('activerecord.attributes.museum_item.notes') %></b>
  <%= @museum_item.notes %>
</p>

<%= link_to t(:back), museum_items_path, :class => 'button' %>
<%= link_to t(:edit), edit_museum_item_path(@museum_item), :class => 'button' %>